name: Test PAGASA Parser

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test-parser:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Test PAGASA Parser
        run: python test_pagasa.py
